name: Create Artwork
on:
  issues:
    types: [opened, edited]
jobs:
  rename-issue-title:
    runs-on: ubuntu-latest
    steps:
      - name: Extract App ID
        id: extract_app_id
        run: |
          echo "app_id=$(echo '${{ github.event.issue.body }}' | grep -oP '(?<=app_id: ).*')" >> $GITHUB_ENV
      - name: Rename Issue Title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X PATCH \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
            -d '{"title":"[Request] '${{ env.app_id }}'"}'