name: Update Artwork CSS

on:
  workflow_dispatch:

jobs:
  update-css:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update CSS files
        run: |
          # Find all index.css files in artworks directory
          find artworks -type f -name "index.css" | while read -r css_file; do
            cp templates/index.css "$css_file"
            echo "Updated $css_file"
          done

      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add artworks/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update all artwork index.css files from templates/index.css"
            git push
          fi

      - name: Trigger Weekly Release Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'weekly-release.yml',
                ref: 'main'
            });